# Generated by Django 5.1.1 on 2025-04-07 20:24

import accounts.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        max_length=17,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        max_length=1,
                    ),
                ),
                ("age", models.IntegerField(blank=True, null=True)),
                ("address", models.CharField(blank=True, max_length=50)),
                (
                    "blood_group",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("O-", "O-"),
                            ("O+", "O+"),
                            ("A-", "A-"),
                            ("A+", "A+"),
                            ("B-", "B-"),
                            ("B+", "B+"),
                            ("AB-", "AB-"),
                            ("AB+", "AB+"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "med_reps",
                    models.FileField(blank=True, upload_to="profile/med_reps"),
                ),
                ("specialization", models.CharField(max_length=100)),
                ("registration_number", models.IntegerField()),
                ("years_of_experience", models.IntegerField()),
                ("next_of_kin", models.CharField(max_length=50)),
                ("insurance_number", models.IntegerField()),
                (
                    "certifications",
                    models.FileField(upload_to=accounts.models.user_directory_path),
                ),
                (
                    "avatar",
                    models.ImageField(
                        default="default.jpg", upload_to="profile_images"
                    ),
                ),
                ("bio", models.TextField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
